### ISSUE TITLE
Create empty fragments

### ISSUE THREAD

**Issue by AppFitnessTeam** [AppFitnessTeam/project-fitness-constructor#3]
Need to create empty fragment (Kotlin class and layout) for Nav Graph
Fragments list:

- WorkoutListFragment - start fragment with list of workouts from database
- WorkoutFragment - fragment with list of exercises
- ExerciseFragment - fragment for user to use during workout
- StatisticFragment - fragment with statistic
- AppSettingsFragment - fragment with settings of app

**Comment by MarDSoul** [comment]
I've made a BaseFragment abstract class, and it can extends other fragments of BaseFragment, such as:
`class WorkoutFragment : BaseFragment<FragmentWorkoutBinding>(FragmentWorkoutBinding::inflate)`

**Comment by AppFitnessTeam** [comment]
OK!

**Comment by DmitrySergienko** [comment]
Ok, I will update all fragments when the Base frag will be available
