### ISSUE TITLE
Add database

### ISSUE THREAD

**Issue by MarDSoul** [AppFitnessTeam/project-fitness-constructor#32]
### Add a database table, with option to attach fields (parameters).

1. Create SQLite database with exercises and inject it into assert resources.
2. Create Room classes (dao, entities, database)

Example Room entity:
```
@Entity(
    tableName = "exercises_list"
)
data class EntityExercise(
    @PrimaryKey(autoGenerate = true) val id: Long,
    val name: String,
    val iconId: Int
)
```

**Comment by Pushin1007** [comment]
fixed bug with workout_id 
What is HILT ?
Let's not split TDAO yet
